name: Inspect [linters, tests]

on:
  [workflow_dispatch, push]
jobs:
  go-inspect:
    name: Inspect
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # see: https://golangci-lint.run/usage/configuration/#config-file
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
      - name: go test
        run: go test ./...
      - name: k3d-action-test
        run: k3d cluster create k3d-action --wait --agents 1 --no-lb --k3s-server-arg "--no-deploy=traefik,servicelb,metrics-server"

